"""Initial schema

Revision ID: bebbd609489f
Revises: 
Create Date: 2026-01-25 05:17:05.637656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bebbd609489f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('cedula')
    )
    op.create_table('inventario',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('es_favorito', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('venta',
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_venta')
    )
    op.create_table('vehiculo',
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id_cliente'], ),
    sa.PrimaryKeyConstraint('placa')
    )
    op.create_table('venta_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['inventario.id_producto'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id_venta'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orden_trabajo',
    sa.Column('numeroOT', sa.Integer(), nullable=False),
    sa.Column('placa_vehiculo', sa.String(length=20), nullable=False),
    sa.Column('sintomas', sa.Text(), nullable=True),
    sa.Column('categoria_color', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=True),
    sa.Column('monto_mano_obra', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['placa_vehiculo'], ['vehiculo.placa'], ),
    sa.PrimaryKeyConstraint('numeroOT')
    )
    op.create_table('factura',
    sa.Column('nro_factura', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=True),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=True),
    sa.Column('total_final', sa.Float(), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['orden_id'], ['orden_trabajo.numeroOT'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id_venta'], ),
    sa.PrimaryKeyConstraint('nro_factura')
    )
    op.create_table('orden_detalle_repuesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_snapshot', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['orden_trabajo.numeroOT'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['inventario.id_producto'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orden_detalle_repuesto')
    op.drop_table('factura')
    op.drop_table('orden_trabajo')
    op.drop_table('venta_detalle')
    op.drop_table('vehiculo')
    op.drop_table('venta')
    op.drop_table('user')
    op.drop_table('inventario')
    op.drop_table('cliente')
    # ### end Alembic commands ###
